name: stm32 port

on:
  push:
  pull_request:
    paths:
      - '.github/workflows/*.yml'
      - 'tools/**'
      - 'py/**'
      - 'extmod/**'
      - 'shared/**'
      - 'lib/**'
      - 'drivers/**'
      - 'ports/stm32/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_pyb:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Install packages
      run: source tools/ci.sh && ci_stm32_setup
    - name: Build
      run: source tools/ci.sh && ci_stm32_pyb_build

  build_nucleo:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Install packages
      run: source tools/ci.sh && ci_stm32_setup
    - name: Build
      run: source tools/ci.sh && ci_stm32_nucleo_build
