name: qemu-arm port

on:
  push:
  pull_request:
    paths:
      - '.github/workflows/*.yml'
      - 'tools/**'
      - 'py/**'
      - 'extmod/**'
      - 'shared/**'
      - 'lib/**'
      - 'drivers/**'
      - 'ports/qemu-arm/**'
      - 'tests/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install packages
      run: source tools/ci.sh && ci_qemu_arm_setup
    - name: Build and run test suite
      run: source tools/ci.sh && ci_qemu_arm_build
    - name: Print failures
      if: failure()
      run: grep --before-context=100 --text "FAIL" ports/qemu-arm/build/console.out
