name: zephyr port

on:
  push:
  pull_request:
    paths:
      - '.github/workflows/ports_zephyr.yml'
      - 'tools/**'
      - 'py/**'
      - 'extmod/**'
      - 'shared/**'
      - 'lib/**'
      - 'ports/zephyr/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install packages
      run: source tools/ci.sh && ci_zephyr_setup
    - name: Install Zephyr
      run: source tools/ci.sh && ci_zephyr_install
    - name: Build
      run: source tools/ci.sh && ci_zephyr_build
