name: Build CI

on:
  push:
  pull_request:
    paths:
    - 'code/**'
    - 'tests/**'
    - '.github/workflows/**'
  release:
    types: [published]
  check_suite:
    types: [rerequested]

jobs:
  micropython:
    strategy:
        matrix:
            os:
                - ubuntu-16.04
                - macos-10.14
    runs-on: ${{ matrix.os }}
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Versions
      run: |
        gcc --version
        python3 --version
    - name: Checkout ulab
      uses: actions/checkout@v1

    - name: Checkout micropython repo
      uses: actions/checkout@v2
      with:
        repository: micropython/micropython
        path: micropython

    - name: Run build.sh
      run: ./build.sh

#  circuitpython:
#    strategy:
#        matrix:
#            os:
#                - ubuntu-16.04
#                - macos-10.14
#    runs-on: ${{ matrix.os }}
#    steps:
#    - name: Dump GitHub context
#      env:
#        GITHUB_CONTEXT: ${{ toJson(github) }}
#      run: echo "$GITHUB_CONTEXT"
#    - name: Set up Python 3.5
#      uses: actions/setup-python@v1
#      with:
#        python-version: 3.8
#
#    - name: Versions
#      run: |
#        gcc --version
#        python3 --version
#
#    - name: Checkout ulab
#      uses: actions/checkout@v1
#
#    - name: Install requirements
#      run: |
#        if type -path apt-get; then
#            sudo apt-get install gettext
#        else
#            brew install gettext
#            echo >>$GITHUB_PATH /usr/local/opt/gettext/bin
#        fi
#
#    - name: Run build-cp.sh
#      run: ./build-cp.sh
